package com.google.codeu.models;

import java.net.URL;
import java.util.UUID;

/**
 * Class representing an image in a post.
 */
public class PostImage {

    private UUID id;
    private UUID postId;
    private URL imageUrl;
    private String imageDescription;

    /**
     * Construct a new <code>PostImage</code> object with the image's URL, the
     * post's ID and its description. Its ID will be randomly generated by the
     * server.
     * 
     * @param postId           The post's ID.
     * @param imageURL         The image's URL.
     * @param imageDescription The image's description.
     */
    public PostImage(UUID postId, URL imageURL, String imageDescription) {
        this(UUID.randomUUID(), postId, imageURL, imageDescription);
    }

    /**
     * Construct a new <code>PostImage</code> in full details.
     * 
     * @param id               The image's id.
     * @param postId           The post's ID.
     * @param imageURL         The image's URL.
     * @param imageDescription The image's description.
     */
    public PostImage(UUID id, UUID postId, URL imageURL, String imageDescription) {
        this.id = id;
        this.postId = id;
        this.imageUrl = imageURL;
        this.imageDescription = imageDescription;
    }

    public UUID getId() {
        return id;
    }

    public UUID getPostId() {
        return postId;
    }

    public URL getImageUrl() {
        return imageUrl;
    }

    public String getImageDescription() {
        return imageDescription;
    }
}